#include "ascii.hpp"


Xf::Ascii::Chartable Xf::Ascii::_array = {

	SPACE,
	EXCLAMATION,
	DOUBLE_QUOTE,
	HASHTAG,
	DOLLAR,
	PERCENT,
	AMPERSAND,
	SINGLE_QUOTE,
	LEFT_PARENTHESIS,
	RIGHT_PARENTHESIS,
	ASTERISK,
	PLUS,
	COMMA,
	MINUS,
	PERIOD,
	SLASH,

	NUMBER, NUMBER, NUMBER, NUMBER,
	NUMBER, NUMBER, NUMBER, NUMBER,
	NUMBER, NUMBER,

	COLON,
	SEMICOLON,
	LESS,
	EQUALITY,
	GREATER,
	QUESTION,
	AT,

	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER,

	LEFT_SQUARE,
	BACKSLASH,
	RIGHT_SQUARE,
	CIRCUMFLEX,
	UNDERSCORE,
	ACCENT,

	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER, LETTER, LETTER,
	LETTER, LETTER,

	LEFT_CURLY,
	PIPE,
	RIGHT_CURLY,
	TILDE

};


